---
title: "RREAS Original"
author: "Rebecca Howard"
date: "2022-08-25"
output: html_document
---

```{r setup, include = FALSE}
### Load libraries
library(readxl)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(grid)
library(reshape2)
library(here)
library(rerddap)
library(tidync)
library(ncdf4)
library(sf)
library(lubridate)
```

Functions

```{r}
# Get data into appropriate format
clean_catch <- function(data_list, i){
  data_frame <- as.data.frame(data_list[[i]])
  names(data_frame) <- tolower(names(data_frame))
  names(data_frame)[names(data_frame) == 'net_in_latdd'] <- 'lat'
  names(data_frame)[names(data_frame) == 'net_in_londd'] <- 'lon'
  names(data_frame)[names(data_frame) == 'total_no'] <- 'catch'
  return(data_frame)
}

clean_sp <- function(data_list, i){
  data_frame <- as.data.frame(data_list[[i]])
  names(data_frame) <- tolower(names(data_frame))
  names(data_frame)[names(data_frame) == 'net_in_latdd'] <- 'lat'
  names(data_frame)[names(data_frame) == 'net_in_londd'] <- 'lon'
  names(data_frame)[names(data_frame) == 'total_no'] <- 'catch'
  names(data_frame)[names(data_frame) == 'nmeas'] <- 'num_measured'
  names(data_frame)[names(data_frame) == 'exp'] <- 'haul_exp'
  return(data_frame)
}

# Combine the grouped length data with the catch data
merge_lengths <- function(catch, hauls, subset, RREAS_means, PRS_means){
  data <- merge(catch,
                subset[, c("haul_no", "cruise", "small", "large")],
                by = c("haul_no", "cruise"),
                all.x = TRUE) # Add the catch info to the length data
  data_zero <- data %>% mutate(small = ifelse(is.na(small), 0, small),
                               large = ifelse(is.na(large), 0, large)) %>%
    filter(catch == small + large)
  data_id <- merge(hauls[, c("haul_no", "cruise", "ctd_index")],
                   data_zero,
                   by = c("haul_no", "cruise"),
                   all.y = TRUE)
  data_ctd <- merge(data_id,
                    RREAS_means,
                    by = c('cruise', 'ctd_index', 'year'),
                    all.x = TRUE) # match RREAS ctds
  data_ctd_all <- merge(data_ctd,
                        PRS_means,
                        by.x = c('numeric_date', 'station'),
                        by.y = c('date', 'swfcs.station'),
                        all.x = TRUE)
  data_comb <- mutate(data_ctd_all,
                      temperature = coalesce(temperature, temperature_c),
                      salinity = coalesce(salinity, salinity_psu))
  return(data_comb)
}

# Group into two size classes
coalesce_by_column <- function(data) {
  return(dplyr::coalesce(!!! as.list(data)))
  }
  
size_calc <- function(sp, size){
  sizes <- mutate(sp, size_class = case_when(std_length <= size ~ "small",
                                             std_length > size ~ "large",
                                             is.na(std_length) ~ "NA")) 
  subset <- sizes %>% 
    dplyr::group_by(numeric_date, station, haul_no, haul_exp, size_class, cruise, catch) %>%
    mutate(size_class = factor(size_class, levels = c("small", "large", "NA"))) %>%
    summarise(size_count = length(size_class)) %>%
    mutate(size_subset = size_count * haul_exp) %>%
    tidyr::pivot_wider(names_from = size_class,
                       values_from = size_subset)
  
  subset_coalesce <- subset %>% group_by(numeric_date, station, haul_no, cruise) %>%
    summarise_all(coalesce_by_column) 
  
  subset_final <- subset_coalesce %>% 
    mutate_at(c("small", "large"), ~tidyr::replace_na(., 0))

  return(subset_final)
}

# Plot relevant variables
plot_variables <- function(data){
  plot(table(data$year[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Year',
       main = '')
  plot(table(data$jday[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Day of Year',
       main = '')
  plot(table(data$lat[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Latitude',
       main = '')
  plot(table(data$lon[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Longitude',
       main = '')
  plot(table(data$strata[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Strata',
       main = '')
  hist(data$catch, 
       breaks = 100,
       main = '',
       xlab = 'Catch') 
}

# Filter out needed pre-recruit species
species_filter <- function(data, species){
  data %>%
    select(c('cruise', 'date', 'year', 'month',
             'day', 'tow_depth', 'latitude', 
             'longitude', 'surface_temp', 
             'species', 'numeric_date')) %>%
    rename(larval_count = species) %>%
    mutate(larval_count = ifelse(is.na(larval_count), 0, larval_count)) %>%
    mutate(larval_count = as.numeric(as.character(larval_count)))
}

# Match ROMS hindcast to the fish data
hindcast_match <- function(data, roms, ssh, a, b){
  data[, c(a, b)] <- as.data.frame(RANN::nn2(roms[, c('lat', 'lon', 'month', 'year')],
                                             data[, c('lat', 'lon', 'month', 'year')],
                                             k = 1))
  data$roms_temperature <- as.data.frame(roms)[c(data$nn.idx), 5] # Match nearest temp
  data$roms_salinity <- as.data.frame(roms)[c(data$nn.idx), 4]
  data$roms_ssh <- as.data.frame(roms)[c(data$nn.idx), 6]
  data$ssh_anom <- as.data.frame(roms)[c(data$nn.idx), 21]
  data$sss_anom <- as.data.frame(roms)[c(data$nn.idx), 23]
  data$sst_anom <- as.data.frame(roms)[c(data$nn.idx), 22]
  data$year_ssh <- as.data.frame(roms)[c(data$nn.idx), 25]
  data[, c(a, b)] <- as.data.frame(RANN::nn2(ssh[, c('latitude', 'longitude', 'date')],
                                             data[, c('lat', 'lon', 'date')],
                                             k = 1))
  data$ssh_nc <- as.data.frame(ssh)[c(data$nn.idx), 10]
  data <- data[-c(a, b)] # remove extra columns before predicting
  return(data)
}
```

Data from emails
```{r}
# Load data
anch_exl_data <- here('data', 'anch_yoy.xlsx')
excel_sheets(path = anch_exl_data) # view the worksheets
anch_tab_names <- excel_sheets(path = anch_exl_data)

anch_data_list <- lapply(anch_tab_names, function(x) read_excel(path = anch_exl_data, sheet = x))

anch_catch <- clean_catch(anch_data_list, 1)
anch_catch$numeric_date <- as.numeric(format(as.Date(anch_catch$haul_date, format = "%Y-%m-%d"),
                                           "%m%d%Y"))
anch_catch$date <- as.Date(anch_catch$haul_date)
anch_sp <- clean_sp(anch_data_list, 2)
anch_sp$numeric_date <- as.numeric(format(as.Date(anch_sp$haul_date, format = "%Y-%m-%d"),
                                           "%m%d%Y"))
anch_sp$date <- as.Date(anch_sp$haul_date)

new_data <- here('data', 'datatoRHoward.xlsx')
excel_sheets(path = new_data) # view the worksheets
new_tab_names <- excel_sheets(path = new_data)
new_data_list <- lapply(new_tab_names, 
                          function(x) read_excel(path = new_data, 
                                                 sheet = x, 
                                                 col_types = 'text'))

other_exl_data <- here('data', 'rockfish_dab_hake.xlsx')
excel_sheets(path = other_exl_data) # view the worksheets
other_tab_names <- excel_sheets(path = other_exl_data)

other_data_list <- lapply(other_tab_names, 
                          function(x) read_excel(path = other_exl_data, 
                                                 sheet = x, 
                                                 col_types = 'text'))

hake_short_widow_catch <- clean_catch(new_data_list, 1)
squid_catch <- clean_catch(new_data_list, 2)
squid_sp <- clean_sp(new_data_list, 3)
widow_sp_new <- clean_sp(new_data_list, 4)
sbly_sp_new <- clean_sp(new_data_list, 5)
hake_sp_new <- clean_sp(new_data_list, 6)

other_catch <- clean_catch(other_data_list, 1)
other_sp <- clean_sp(other_data_list, 2)

other_names_catch <- c('haul_no', 'year', 'month', 'jday',
                       'station', 'lat', 'lon', 'bottom_depth', "dab")
other_names_sp <- c('haul_no', 'year', 'month', 'jday', 'station', 
                  'lat', 'lon', 'bottom_depth', 'catch', 'num_measured', 
                  'haul_exp', 'std_length', 'species')
new_names_catch <- c('haul_no', 'year', 'month', 'jday', 
                     'station', 'lat', 'lon', 'bottom_depth', 
                     'yoy_pacific_hake', 'yoy_shortbelly', 'yoy_widow')
squid_names_catch <- c('haul_no', 'year', 'month', 'jday', 
                       'station', 'lat', 'lon', 'bottom_depth', 'market_squid')
col_names_sp <- c('haul_no', 'year', 'month', 'jday', 'station', 
                  'lat', 'lon', 'bottom_depth', 'catch', 'num_measured', 
                  'haul_exp', 'std_length')

date_conversion <- function(catch, names){
  catch[names] <- sapply(catch[names], as.numeric) # changes NA's to actual NA
  new_catch <- catch %>% mutate(date = strptime(paste(as.numeric(year), as.numeric(jday)), format = "%Y%j"))
  new_catch$numeric_date <- as.numeric(format(as.Date(new_catch$date, format = "%Y%j"),
                                              "%m%d%Y"))
  new_catch$date <- as.Date(new_catch$date)
  return(new_catch)
}

hws_catch <- date_conversion(hake_short_widow_catch, new_names_catch)
dab_catch <- date_conversion(other_catch, other_names_catch)
squid_catch <- date_conversion(squid_catch, squid_names_catch)
squid_sp <- date_conversion(squid_sp, col_names_sp)
hake_sp <- date_conversion(hake_sp_new, col_names_sp)
widow_sp <- date_conversion(widow_sp_new, col_names_sp)
sbly_sp <- date_conversion(sbly_sp_new, col_names_sp)
dab_sp <- date_conversion(other_sp, other_names_sp)

dab_catch <- dab_catch %>% 
  dplyr::select(-c('shortbelly', 'hake', 'widow')) %>%
  rename(catch = dab) %>%
  filter(year > 2010)

# Keep NA's because these are hauls with no catch at all
# Have hauls with 0 measurements as well, but catches (so if num_measured > 1 but catch = 0 then remove)
widow_sp <- filter(widow_sp, 
                   std_length > 16 & std_length < 65 | is.na(std_length), 
                   num_measured > 0 | catch == 0)
sbly_sp <- filter(sbly_sp, 
                  std_length > 10 & std_length < 79 | is.na(std_length), 
                  num_measured > 0 | catch == 0)
hake_sp <- filter(hake_sp, 
                  std_length > 14 & std_length < 82 | is.na(std_length), 
                  num_measured > 0 | catch == 0)
squid_sp <- filter(squid_sp, 
                   std_length > 10 & std_length < 140 | is.na(std_length), 
                   num_measured > 0 | catch == 0)
dab_sp <- filter(dab_sp, species == 147, year > 2010, 
                 std_length > 15 & std_length < 56 | is.na(std_length), 
                 num_measured > 0 | catch == 0)
anch_sp <- filter(anch_sp, 
                  std_length > 20 & std_length < 86 | is.na(std_length), 
                  num_measured > 0 | catch == 0)

rm(list = c('anch_data_list', 'other_catch', 
            'other_data_list', 'other_sp',
            'anch_exl_data', 'anch_tab_names',
            'col_names_catch', 'col_names_sp',
            'other_exl_data', 'other_tab_names'))
```

```{r}
# Consolidate lengths
anch_subset <- size_calc(anch_sp, 35)
widow_subset <- size_calc(widow_sp, 31) 
sbly_subset <- size_calc(sbly_sp, 35)
dab_subset <- size_calc(dab_sp, 25)
hake_subset <- size_calc(hake_sp, 35)

anch_subset[is.na(anch_subset)] <- 0
widow_subset[is.na(widow_subset)] <- 0
sbly_subset[is.na(sbly_subset)] <- 0
dab_subset[is.na(dab_subset)] <- 0
hake_subset[is.na(hake_subset)] <- 0
```

```{r}
# # Extract CTD data
# # RREAS
RREAS_CTD_info <- info('FED_Rockfish_CTD')

RREAS_ctds <- tabledap(RREAS_CTD_info,
                       fields = c('cruise', 'ctd_index',
                                  'temperature', 'salinity',
                                  'station', 'ctd_depth', 'time'),
                       'ctd_depth<=10')

RREAS_cols <- c('temperature', 'salinity')
RREAS_ctds[RREAS_cols] <- sapply(RREAS_ctds[RREAS_cols], as.numeric)

RREAS_ctd_means <- RREAS_ctds %>%
  mutate(date = format(as.POSIXct(time, tz = "UTC", format = "%Y-%m-%d")),
         year = lubridate::year(date)) %>%
  group_by(cruise, ctd_index, year) %>%
  summarise_at(vars('temperature', 'salinity'), mean) %>%
  mutate_all(~ifelse(is.nan(.), NA, .))

# Pre-recruit
PRS_ctds <- read.csv(here::here('data', 'Prerecruit_env.csv'))[, -1]

PRS_avg_ctds <- PRS_ctds %>%
  filter(depth_m <= 10) %>%
  group_by(date, swfcs.station) %>%
  mutate(date = as.numeric(format(as.Date(date,
                                          format = "%Y-%m-%d"),
                                  "%m%d%Y"))) %>%
  summarise_at(vars('temperature_c', 'salinity_psu'), mean) %>%
  mutate_all(~ifelse(is.nan(.), NA, .))
```

```{r}
# Match to haul level data 
haul_data <- read_excel(here('data', 'haul_data_through2021.xlsx'))
names(haul_data) <- tolower(names(haul_data))

merge_anch <- merge_lengths(anch_catch, haul_data, anch_subset, RREAS_ctd_means, PRS_avg_ctds)
merge_widw <- merge_lengths(widow_catch, haul_data, widow_subset, RREAS_ctd_means, PRS_avg_ctds)
merge_sbly <- merge_lengths(sbly_catch, haul_data, sbly_subset, RREAS_ctd_means, PRS_avg_ctds)
merge_dab <- merge_lengths(dab_catch, haul_data, dab_subset, RREAS_ctd_means, PRS_avg_ctds)
merge_hake <- merge_lengths(hake_catch, haul_data, hake_subset, RREAS_ctd_means, PRS_avg_ctds)
```

```{r}
nep <- tidync(here('data','nep_srf_1995-2020.nc'))
nep_var <- nep %>% 
  hyper_tibble() 

nep_var <- nep_var %>%
  dplyr::select(-s_rho)

nep_height <- nep %>% 
  activate(zeta) %>% 
  hyper_tibble()

nep_hindcast <- merge(nep_var, nep_height, by = c("xi_rho", "eta_rho", "ocean_time"))

# Currently only one layer of s_rho, will need to extract top layer if this changes
nep_hindcast$lon <- lons[cbind(nep_hindcast$xi_rho, nep_hindcast$eta_rho)]
nep_hindcast$lat <- lats[cbind(nep_hindcast$xi_rho, nep_hindcast$eta_rho)]

nep_hindcast$datetime <- as.POSIXct(nep_hindcast$ocean_time, origin = "1900-01-01 00:00:00", tz = "GMT")

# Split out months, weeks, years
nep_hindcast$date <- as.Date(nep_hindcast$datetime) 
nep_hindcast$month <- month(nep_hindcast$date)
nep_hindcast$week <- week(nep_hindcast$date)
nep_hindcast$year <- year(nep_hindcast$date)

# Reduce to only data near the sample locations
hindcast_trim <- nep_hindcast %>%
  mutate(numeric_date = as.numeric(format(as.Date(date, 
                                                  format = "%Y-%m-%d"),
                                          "%m%d%Y")),
         lon = case_when(lon >= 180 ~ lon - 360,
                         lon < 180 ~ lon)) %>%
  filter(between(month, 4, 8) & # must use between, no %in% for numeric
           between(lat, 32.7, 47.6) &
           between(lon, -125.4, -117.3))
```

```{r}
# Get means by month for each unique lat/lon combo
# Subtract value at each location/time by monthly value then divide by SD
hindcast_anom <- hindcast_trim %>%
  group_by(month, lat, lon) %>%
  mutate(ssh_month = mean(zeta),
         sst_month = mean(temp),
         sss_month = mean(salt),
         ssh_sd = sd(zeta),
         sst_sd = sd(temp),
         sss_sd = sd(salt)) %>%
  mutate(ssh_anom = (zeta - ssh_month)/ssh_sd,
         sst_anom = (temp - sst_month)/sst_sd,
         sss_anom = (salt - sss_month)/sss_sd)
```

```{r}
# Calculate anomalies
library(marmap)
ccs_depth <- getNOAA.bathy(-125.4, -117.3, 32.7, 47.6) # get depths
depth_df <- fortify.bathy(ccs_depth)

# Match to the hindcast
hindcast_anom[, c(24, 25)] <- as.data.frame(RANN::nn2(depth_df[, c('y', 'x')],
                                                      hindcast_anom[, c('lat', 'lon')],
                                                      k = 1))
hindcast_anom$depth <- as.data.frame(depth_df)[c(hindcast_anom$nn.idx), 3] 
hindcast_anom <- hindcast_anom[-c(24, 25)]

# Remove the values not on the shelf, between May and July
hindcast_depths <- filter(hindcast_anom,
                          between(depth, -100, 0),
                          between(month, 5, 7)) 

# Calculate average yearly values per year
hindcast_year <- hindcast_depths %>%
  group_by(year) %>%
  summarise(year_ssh = mean(ssh_anom, na.rm = TRUE),
            year_temp = mean(sst_anom, na.rm = TRUE),
            year_salt = mean(sss_anom, na.rm = TRUE))

# Match back to the main data frame
hindcast_anom$year_ssh <- hindcast_year$year_ssh[match(hindcast_anom$year,
                                                       hindcast_year$year)]

saveRDS(hindcast_anom, file = "../data/hindcast_means.Rdata")
```

```{r}
# Import the AVISO + TG files
ssh_files <- list.files(path = "C:/Users/howar/Documents/Oregon State/ELH_WestCoast/data/aviso_tg_ssh/")

prestring <- "C:/Users/howar/Documents/Oregon State/ELH_WestCoast/data/aviso_tg_ssh/"

ssh_df <- list()

for(i in ssh_files){
  ssh_df[[i]] <- paste0(prestring, i)
  ssh_df
}

ssh_dat <- list()

for(i in ssh_df){
  ssh_dat[[i]] <- tidync(i) %>%
    hyper_tibble(select_var = "sea_surface_height_above_sea_level")
  ssh_dat
}

ssh <- bind_rows(ssh_dat)
ssh$date <- as.Date(ssh$time, origin = "1970-01-01")
ssh$lon <- case_when(ssh$longitude >= 180 ~ ssh$longitude - 360,
                     ssh$longitude < 180 ~ ssh$longitude)
ssh$lat <- ssh$latitude
ssh$month <- month(ssh$date)
ssh$year <- year(ssh$date)

ssh_filter <- ssh %>% filter(between(month, 4, 8) & # must use between, no %in% for numeric
                               between(latitude, 32.7, 47.6) &
                               between(longitude, -125.4, -117.3))

ssh_anom <- ssh_filter %>%
  group_by(month, latitude, longitude) %>%
  mutate(ssh_month = mean(sea_surface_height_above_sea_level),
         ssh_sd = sd(sea_surface_height_above_sea_level)) %>%
  mutate(ssh_anom = (sea_surface_height_above_sea_level - ssh_month)/ssh_sd)

saveRDS(ssh_anom, file = "../data/ssh_data.Rdata")
```

```{r}
# Match to the fish data
hindcast_anom <- readRDS("../data/hindcast_means.Rdata")
ssh_anom <- readRDS("../data/ssh_data.Rdata")

# No ROMS past 2018 right now
yoy_anch <- hindcast_match(merge_anch, hindcast_anom, ssh_anom, 29, 30)
yoy_dab <- hindcast_match(merge_dab, hindcast_anom, ssh_anom, 29, 30)
yoy_hake <- hindcast_match(merge_hake, hindcast_anom, ssh_anom, 29, 30)
yoy_sbly <- hindcast_match(merge_sbly, hindcast_anom, ssh_anom, 29, 30)
yoy_widw <- hindcast_match(merge_widw, hindcast_anom, ssh_anom, 29, 30)
```

```{r, warning = FALSE}
# ggplot(yoy_sbly, aes(temperature, roms_temperature)) +
#   geom_point() +
#   geom_smooth(method = lm, se = FALSE)
```

```{r}
# Save final dataframes
saveRDS(yoy_anch, file = "../data/yoy_anch.Rdata")
saveRDS(yoy_widw, file = "../data/yoy_widw.Rdata")
saveRDS(yoy_sbly, file = "../data/yoy_sbly.Rdata")
saveRDS(yoy_dab, file = "../data/yoy_dab.Rdata")
saveRDS(yoy_hake, file = "../data/yoy_hake.Rdata")
```

```{r}
# Make maps of catches
west_coast <- map_data("usa")
```

```{r}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_polygon(data = west_coast,
               aes(x = long, y = lat, group = group)) +
  geom_point(data = hindcast_trim, aes(x = lon, y = lat, color = temp),
             size = 5, alpha = 1 / 15, shape = 19) +
  scale_color_gradient(low = "#023858", high = "red4") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))
```

```{r}
par(mfrow = c(2, 3))
plot_variables(anch_catch)

par(mfrow = c(2, 3))
plot_variables(widow_catch)

par(mfrow = c(2, 3))
plot_variables(sbly_catch)

par(mfrow = c(2, 3))
plot_variables(dab_catch)

par(mfrow = c(2, 3))
plot_variables(hake_catch)
```

```{r}
# Look at pattern of days by latitude
ggplot(anch_catch) +
  geom_point(aes(jday, lat))

ggplot(widow_catch) +
  geom_point(aes(jday, lat))

ggplot(sbly_catch) +
  geom_point(aes(jday, lat))

ggplot(dab_catch) +
  geom_point(aes(jday, lat))

ggplot(hake_catch) +
  geom_point(aes(jday, lat))
```

```{r}
ggplot(anch_sp) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(widow_sp) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(sbly_sp) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(dab_sp) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(hake_sp) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2) # may want to remove hake over 70 mm
```

```{r}
anch_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

widow_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

sbly_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

dab_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

hake_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()
```

```{r, fig.width = 10, fig.height = 5, warning = FALSE, echo = FALSE}
# polish boxplot for depth/length
anch_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 3750, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Anchovy by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
widow_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 4000, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Widow Rockfish by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750", "3750-4000")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
sbly_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 4000, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Shortbelly Rockfish by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750", "3750-4000")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
dab_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 4000, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Sanddab by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750", "3750-4000")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
hake_sp %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 4000, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Hake by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750", "3750-4000")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
# Investigate latitude
ggplot(anch_sp) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(widow_sp) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(sbly_sp) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(dab_sp) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)

ggplot(hake_sp) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)
```

```{r}
anch_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

widow_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

sbly_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

dab_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

hake_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()
```

```{r, fig.width = 10, fig.height = 5, warning = FALSE, echo = FALSE}
# polish boxplot for lat/length
anch_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Anchovy by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
widow_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Widow Rockfish by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
sbly_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Shortbelly Rockfish by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
dab_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Sanddab by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r}
hake_sp %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 49, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Hake by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = anch_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_anchplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = anch_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_anchplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = anch_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_anchplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = anch_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = widow_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_widowplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = widow_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_widowplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = widow_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_widowplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = widow_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = sbly_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_sblyplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = sbly_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_sblyplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = sbly_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_sblyplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = sbly_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_dabplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_dabplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_dabplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_hakeplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_hakeplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_hakeplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE}
grid.newpage()
# Create layout: nrow = 2, ncol = 2
pushViewport(viewport(layout = grid.layout(2, 2)))
# A helper function to define a region on the layout
define_region <- function(row, col){
  viewport(layout.pos.row = row, layout.pos.col = col)
} 
# Arrange the plots
print(yoy_anchplot3, vp = define_region(2, 1:2))
print(yoy_anchplot1, vp = define_region(1, 1))
print(yoy_anchplot2, vp = define_region(1, 2))

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
print(yoy_widowplot3, vp = define_region(2, 1:2))
print(yoy_widowplot1, vp = define_region(1, 1))
print(yoy_widowplot2, vp = define_region(1, 2))

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
print(yoy_sblyplot3, vp = define_region(2, 1:2))
print(yoy_sblyplot1, vp = define_region(1, 1))
print(yoy_sblyplot2, vp = define_region(1, 2))

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
print(yoy_dabplot3, vp = define_region(2, 1:2))
print(yoy_dabplot1, vp = define_region(1, 1))
print(yoy_dabplot2, vp = define_region(1, 2))

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2)))
print(yoy_hakeplot3, vp = define_region(2, 1:2))
print(yoy_hakeplot1, vp = define_region(1, 1))
print(yoy_hakeplot2, vp = define_region(1, 2))
```
