---
title: "Model Exploration"
author: "Rebecca Howard"
date: "5/6/2022"
output: html_document
---

```{r setup, include = FALSE}
### Load libraries
library(readxl)
library(plyr)
library(tibble)
library(here)
library(ggplot2)
library(lubridate)
library(date)
library(dplyr)
library(maps)
library(mapdata)
library(mgcv)
library(fields)
source("functions/vis_gam_COLORS.R")
```

```{r, include = FALSE, echo = FALSE}
# Histogram of catches
CPUE_hist <- function(species_subset){
  par(mfrow = c(1,2))
  hist(species_subset$lncatch,
       xlab = "log(catch + 1)",
       main = "Raw Data")
  sum(1 * (species_subset$lncatch == 0)) / nrow(species_subset)
  hist(species_subset$lncatch[species_subset$lncatch > 0],
    xlab = "log(catch + 1)",
    main = "Normalized Data")
}

# Gaussian GAMs
catch_GAMs <- function(species_subset){
  year_gam <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy),
                  data = species_subset[species_subset$lncatch > 0,])
  pdo_gam <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(PDO, k = 4),
                  data = species_subset[species_subset$lncatch > 0,])
  npgo_gam <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(NPGO, k = 4),
                  data = species_subset[species_subset$lncatch > 0,])
  oni_gam <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(ONI, k = 4),
                  data = species_subset[species_subset$lncatch > 0,])
  pdo_flex <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = PDO_mean),
                  data = species_subset[species_subset$lncatch > 0,])
  npgo_flex <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = NPGO_mean),
                  data = species_subset[species_subset$lncatch > 0,])
  oni_flex <- gam(lncatch ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = ONI_mean),
                  data = species_subset[species_subset$lncatch > 0,])
  gam_list <- list(year_gam, pdo_gam, npgo_gam, oni_gam, pdo_flex, npgo_flex, oni_flex)
  best_gam <- gam_list[[which.min(sapply(1:length(gam_list),
                                         function(x) min(gam_list[[x]]$aic)))]] # would like to also select by AIC
  return_list <- list(gam_list, best_gam)
} 

# Tweedie GAMs
tweedie_GAMs <- function(species_subset){
  year_gam <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  pdo_gam <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(PDO, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  npgo_gam <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(NPGO, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  oni_gam <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(ONI, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  pdo_flex <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = PDO_mean),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  npgo_flex <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = NPGO_mean),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  oni_flex <- gam(catch + 1 ~ factor(year) + s(lon, lat) + s(bottom_depth, k = 4) + s(doy) + s(lat, lon, by = ONI_mean),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  gam_list <- list(year_gam, pdo_gam, npgo_gam, oni_gam, pdo_flex, npgo_flex, oni_flex)
  best_gam <- gam_list[[which.min(sapply(1:length(gam_list),
                                         function(x) min(gam_list[[x]]$aic)))]] # would like to also select by AIC
  return_list <- list(gam_list, best_gam)
} 

# Plot smooth terms
plot_variable <- function(gam, covariate, bounds, variable, ylabel, yvalues){
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  plot(gam[[2]],
       pages = 0,
       select = covariate, # 1 = year/PDO/NPGO, 2 = lat/lon, 3 = depth, 4 = julian, 5 = temp
       shade = T,
       shade.col = "lemonchiffon3",
       ylim = bounds,
       xlab = variable,
       ylab = ylabel,
       yaxt = yvalues,
       seWithMean = T,
       scale = 0,
       cex.axis = 3,
       cex.lab = 3,
       family = "serif",
       lwd = 2)
}

# Plot distribution
location_plot <- function(gam, species_subset) {
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  myvis_gam(gam[[2]],
            view = c('lon', 'lat'),
            too.far = 0.03,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet" ,
            type = 'response',
            xlim = c(-125.7, -116.5),
            ylim = range(species_subset$lat, na.rm = TRUE) + c(-.4, .5),
            family = "serif",
            xlab = "Longitude",
            ylab = "Latitude",
            main = " ",
            cex.lab = 2.5,
            cex.axis =  2.5)
  maps::map('worldHires',
            add = T,
            col = 'antiquewhite4',
            fill = T)
}

contour_col <- rgb(0, 0, 255, max = 255, alpha = 0, names = "white")
jet.colors <- colorRampPalette(rev(c("#b2182b", "#d6604d", "#f4a582", "#fddbc7",
                                 "#f7f7f7", "#d1e5f0", "#92c5de", "#4393c3", "#2166ac" )))
```

```{r}
# Load data
yoy_hake_catch <- readRDS(file = "../data/yoy_hake_catch.Rdata")
yoy_dab_catch <- readRDS(file = "../data/yoy_dab_catch.Rdata")
adult_dab_catch <- readRDS(file = "../data/adult_dab_catch.Rdata")
yoy_hake_sp <- readRDS(file = "../data/yoy_hake_sp.Rdata")
yoy_dab_sp <- readRDS(file = "../data/yoy_dab_sp.Rdata")
adult_dab_sp <- readRDS(file = "../data/adult_dab_sp.Rdata")
```


```{r}
CPUE_hist(yoy_hake_catch)
CPUE_hist(yoy_dab_catch)
CPUE_hist(adult_dab_catch)
```



#### YOY Hake
### Gaussian on positive catches
## YOY Hake
```{r}
# Base GAM
hake_base <- gam(lncatch ~ factor(year) +
                   s(doy) +
                   s(lat, lon) +
                   s(bottom_depth, k = 4),
                 data = yoy_hake_catch[yoy_hake_catch$lncatch > 0,])
summary(hake_base)

par(mfrow = c(2, 2))
gam.check(hake_base)

par(mfrow = c(2, 2))
plot(hake_base)


# Select best GAM
hake_gam <- catch_GAMs(yoy_hake_catch)
summary(hake_gam[[2]])

par(mfrow = c(2, 2))
gam.check(hake_gam[[2]])

par(mfrow = c(2, 2))
plot(hake_gam[[2]])
```

## YOY Sanddab
```{r}
# Base GAM
yoy_dab_base <- gam(lncatch ~ factor(year) +
                      s(doy) +
                      s(lat, lon) +
                      s(bottom_depth, k = 4),
                    data = yoy_dab_catch[yoy_dab_catch$lncatch > 0,])
summary(yoy_dab_base)

par(mfrow = c(2, 2))
gam.check(yoy_dab_base)

par(mfrow = c(2, 2))
plot(yoy_dab_base)


# Select best GAM
yoy_dab_gam <- catch_GAMs(yoy_dab_catch)
summary(yoy_dab_gam[[2]])

par(mfrow = c(2, 2))
gam.check(yoy_dab_gam[[2]])

par(mfrow = c(2, 2))
plot(yoy_dab_gam[[2]])
```


## Adult Sanddab
```{r}
# Base GAM
adult_dab_base <- gam(lncatch ~ factor(year) +
                        s(doy) +
                        s(lat, lon) +
                        s(bottom_depth, k = 4),
                      data = adult_dab_catch[adult_dab_catch$lncatch > 0,])
summary(adult_dab_base)

par(mfrow = c(2, 2))
gam.check(adult_dab_base)

par(mfrow = c(2, 2))
plot(adult_dab_base)


# Select best GAM
adult_dab_gam <- catch_GAMs(adult_dab_catch)
summary(adult_dab_gam[[2]])

par(mfrow = c(2, 2))
gam.check(adult_dab_gam[[2]])

par(mfrow = c(2, 2))
plot(adult_dab_gam[[2]])
```


### Tweedie on counts
## YOY Hake
```{r}
# Base GAM
hake_base_t <- gam(catch + 1 ~ factor(year) +
                   s(doy) +
                   s(lat, lon) +
                   s(bottom_depth, k = 4),
                 family = tw(link = "log"),
                 method = 'REML',
                 data = yoy_hake_catch)
summary(hake_base_t)

par(mfrow = c(2, 2))
gam.check(hake_base_t)

par(mfrow = c(2, 2))
plot(hake_base_t)


# Select best GAM
hake_gam_t <- tweedie_GAMs(yoy_hake_catch)
summary(hake_gam_t[[2]])

par(mfrow = c(2, 2))
gam.check(hake_gam_t[[2]])

par(mfrow = c(2, 2))
plot(hake_gam_t[[2]])
```

```{r}
plot_variable(hake_gam_t, 
              2, 
              c(-2.5, 4), 
              "Depth", 
              "Species Abundance Anomalies", 
              "s")
dev.copy(jpeg, here('results/yoy_hake_preliminary', 'yoy_hake_depth.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
plot_variable(hake_gam_t, 
              3, 
              c(-2.5, 4), 
              "Day of Year", 
              "", 
              "s")
dev.copy(jpeg, here('results/yoy_hake_preliminary', 'yoy_hake_doy.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
location_plot(hake_gam_t,
              yoy_hake_catch)
image.plot(legend.only = T,
           col = jet.colors(100),
           legend.shrink = 0.2,
           smallplot = c(.28, .31, .11, .24),
           legend.cex = 1.3,
           axis.args = list(cex.axis = 1.8),
           legend.width = 0.8,
           legend.mar = 6,
           zlim = c(min(hake_gam_t[[2]]$fitted.values), 
                    max(hake_gam_t[[2]]$fitted.values)),
           legend.args = list("Count",
                              side = 2, cex = 2))
dev.copy(jpeg, here('results/yoy_hake_preliminary', 'yoy_hake_distribution.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```



## YOY Sanddab
```{r}
# Base GAM
yoy_dab_base_t <- gam(catch + 1 ~ factor(year) +
                      s(doy) +
                      s(lat, lon) +
                      s(bottom_depth, k = 4),
                    family = tw(link = "log"),
                    method = 'REML',
                    data = yoy_dab_catch)
summary(yoy_dab_base_t)

par(mfrow = c(2, 2))
gam.check(yoy_dab_base_t)

par(mfrow = c(2, 2))
plot(yoy_dab_base_t)


# Select best GAM
yoy_dab_gam_t <- tweedie_GAMs(yoy_dab_catch)
summary(yoy_dab_gam_t[[2]])

par(mfrow = c(2, 2))
gam.check(yoy_dab_gam_t[[2]])

par(mfrow = c(2, 2))
plot(yoy_dab_gam_t[[2]])
```

```{r}
plot_variable(yoy_dab_gam_t, 
              2, 
              c(-2.5, 1), 
              "Depth", 
              "Species Abundance Anomalies", 
              "s")
dev.copy(jpeg, here('results/yoy_dab_preliminary', 'yoy_dab_depth.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
plot_variable(yoy_dab_gam_t, 
              3, 
              c(-2.5, 1), 
              "Day of Year", 
              "", 
              "s")
dev.copy(jpeg, here('results/yoy_dab_preliminary', 'yoy_dab_doy.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
location_plot(yoy_dab_gam_t,
              yoy_dab_catch)
image.plot(legend.only = T,
           col = jet.colors(100),
           legend.shrink = 0.2,
           smallplot = c(.28, .31, .11, .24),
           legend.cex = 1.3,
           axis.args = list(cex.axis = 1.8),
           legend.width = 0.8,
           legend.mar = 6,
           zlim = c(min(yoy_dab_gam_t[[2]]$fitted.values), 
                    max(yoy_dab_gam_t[[2]]$fitted.values)),
           legend.args = list("Count",
                              side = 2, cex = 2))
dev.copy(jpeg, here('results/yoy_dab_preliminary', 'yoy_dab_distribution.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```

## Adult Sanddab
```{r}
# Base GAM
adult_dab_base_t <- gam(catch + 1 ~ factor(year) +
                        s(doy) +
                        s(lat, lon) +
                        s(bottom_depth, k = 4),
                      family = tw(link = "log"),
                      method = 'REML',
                      data = adult_dab_catch)
summary(adult_dab_base_t)

par(mfrow = c(2, 2))
gam.check(adult_dab_base_t)

par(mfrow = c(2, 2))
plot(adult_dab_base_t)


# Select best GAM
adult_dab_gam_t <- tweedie_GAMs(adult_dab_catch)
summary(adult_dab_gam_t[[2]])

par(mfrow = c(2, 2))
gam.check(adult_dab_gam_t[[2]])

par(mfrow = c(2, 2))
plot(adult_dab_gam_t[[2]])
```

```{r}
plot_variable(adult_dab_gam_t, 
              2, 
              c(-1.5, 0.5), 
              "Depth", 
              "Species Abundance Anomalies", 
              "s")
dev.copy(jpeg, here('results/adult_dab_preliminary', 'adult_dab_depth.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
plot_variable(adult_dab_gam_t, 
              3, 
              c(-1.5, 0.5), 
              "Day of Year", 
              "", 
              "s")
dev.copy(jpeg, here('results/adult_dab_preliminary', 'adult_dab_doy.jpg'), 
         height = 10, width = 10, units = 'in', res = 200)
dev.off()
```

```{r}
location_plot(adult_dab_gam_t,
              adult_dab_catch)
image.plot(legend.only = T,
           col = jet.colors(100),
           legend.shrink = 0.2,
           smallplot = c(.28, .31, .11, .24),
           legend.cex = 1.3,
           axis.args = list(cex.axis = 1.8),
           legend.width = 0.8,
           legend.mar = 6,
           zlim = c(min(adult_dab_gam_t[[2]]$fitted.values), 
                    max(adult_dab_gam_t[[2]]$fitted.values)),
           legend.args = list("Count",
                              side = 2, cex = 2))
dev.copy(jpeg, here('results/adult_dab_preliminary', 'adult_dab_distribution.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```