---
title: "RREAS Data Exploration"
author: "Rebecca Howard"
output: html_document
---

```{r setup, include = FALSE}
### Load libraries
library(readxl)
library(plyr)
library(tibble)
library(here)
library(ggplot2)
library(lubridate)
library(date)
library(dplyr)
library(maps)
library(mapdata)
library(gridExtra)
library(grid)
library(reshape2)
library(rerddap)
```

Functions
```{r, include = FALSE, echo = FALSE}
# Get data into appropriate format
clean_data <- function(data_list, i){
  data_frame <- as.data.frame(data_list[[i]])
  data_frame <- mutate(data_frame,
                     year = lubridate::year(haul_date),
                     month = lubridate::month(haul_date),
                     day = lubridate::day(haul_date))
  data_frame$doy <- as.numeric(mdy.date(data_frame$month, data_frame$day, 1960))
  data_frame$lncatch <- log(data_frame$catch + 1)
  return(data_frame)
}

# Extract from ERDDAP
extract_ERDDAP <- function(info, variable_list, species){
  tabledap(info,
           fields = variable_list,
           species,
           'maturity="Y"')
  }

# Plot relevant variables
plot_variables <- function(data){
  plot(table(data$year[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Year',
       main = '')
  plot(table(data$doy[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Day of Year',
       main = '')
  plot(table(data$lat[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Latitude',
       main = '')
  plot(table(data$lon[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Longitude',
       main = '')
  plot(table(data$strata[data$catch > 0]),
       ylab = 'Frequency',
       xlab = 'Strata',
       main = '')
  hist(data$catch, 
       breaks = 100,
       main = '',
       xlab = 'Catch') 
}

merge_data <- function(data1, data2){
  merge(data1, data2,
        by.x = c("cruise", "haul_no"),
        by.y = c("cruise", "haul_no"),
        all.x = F, all.y = T)
}

# Add the length ratios to the abundance data set
add_lengths <- function(species, lengths){
  lower <- aggregate(std_length ~ haul_no + cruise,
                         data = lengths,
                         FUN = length,
                         subset = std_length <= median(as.numeric(std_length), na.rm = T))
  yoy <- merge_data(lower, species)
  names(yoy)[names(yoy) == "std_length"] <- "lower_num"
  
  upper <- aggregate(std_length ~ haul_no + cruise,
                         data = lengths,
                         FUN = length,
                         subset = std_length > median(as.numeric(std_length), na.rm = T))
  yoy <- merge_data(upper, yoy)
  names(yoy)[names(yoy) == "std_length"] <- "upper_num"
  
  total <- aggregate(std_length ~ haul_no + cruise,
                         data = lengths,
                         FUN = length)
  yoy <- merge_data(total, yoy)
  names(yoy)[names(yoy) == "std_length"] <- "total_num"
  
  yoy$upper_cpue <- (yoy$upper_num / yoy$total_num) * yoy$catch
  yoy$lower_cpue <- (yoy$lower_num / yoy$total_num) * yoy$catch
  
  yoy$upper_cpue[is.na(yoy$upper_cpue)] <- 0
  yoy$lower_cpue[is.na(yoy$lower_cpue)] <- 0
  
  yoy_filtered <- yoy[yoy$year > min(lengths$year), ] # Length data only from 2012 onward
  return(yoy_filtered)
}
# climate_match <- function(data){
#   data <- merge(data, npgo_index,
#                 by.x = c("year", "month"),
#                 by.y = c("YEAR", "MONTH"),
#                 all.x = T, all.y = F)
#   data <- merge(data, pdo_index,
#                 by.x = c("year", "month"),
#                 by.y = c("year", "month"),
#                 all.x = T, all.y = F)
#   data <- subset(data, select = -c(Date))
#   data <- merge(data, oni_matrix,
#                 by.x = c("year", "month"),
#                 by.y = c("year", "month"),
#                 all.x = T, all.y = F)
#   match_npgo <- match(data$year, npgo_means$YEAR)
#   data$NPGO_mean <- npgo_means$NPGO_mean[match_npgo]
#   match_pdo <- match(data$year, pdo_means$year)
#   data$PDO_mean <- pdo_means$PDO_mean[match_pdo]
#   match_oni <- match(data$year, oni_means$year)
#   data$ONI_mean <- oni_means$ONI_mean[match_oni]
#   return(data)
# }
```

Data from emails
```{r, include = FALSE, echo = FALSE}
# Load data
exl_data <- here::here('data', 'hake_dabs.xlsx')
excel_sheets(path = exl_data) # view the worksheets
tab_names <- excel_sheets(path = exl_data)

data_list <- lapply(tab_names, function(x) read_excel(path = exl_data, sheet = x))

### Clean data
yoy_hake_catch <- clean_data(data_list, 1)
yoy_dab_catch <- clean_data(data_list, 2)
adult_dab_catch <- clean_data(data_list, 3)
yoy_hake_sp <- as.data.frame(data_list[[4]])
yoy_dab_sp <- as.data.frame(data_list[[5]])
adult_dab_sp <- as.data.frame(data_list[[6]])
```

ERDDAP data
```{r}
# ERDDAP extraction
# RREAS
servers()
RREAS_info <- info('FED_Rockfish_Catch')
RREAS_list <- c('latitude', 'longitude',
                'cruise', 'ctd_index', 
                'haul_no', 'station',
                'bottom_depth', 'time',
                'maturity', 'catch')

RREAS_length_info <- info('FED_Rockfish_Length')
RREAS_length_list <- c('cruise', 'haul_no', 
                       'station', 'time',
                       'maturity', 'std_length')

# Create data sets for each species YOY
# Abundance
RREAS_hake <- extract_ERDDAP(RREAS_info, RREAS_list,
                             'sci_name="Merluccius productus"')
RREAS_sanddab <- extract_ERDDAP(RREAS_info, RREAS_list,
                                'sci_name="Citharichthys sordidus"')
RREAS_anchovy <- extract_ERDDAP(RREAS_info, RREAS_list,
                                'sci_name="Engraulis mordax"')
RREAS_widow <- extract_ERDDAP(RREAS_info, RREAS_list,
                              'sci_name="Sebastes entomelas"')
RREAS_shortbelly <- extract_ERDDAP(RREAS_info, RREAS_list,
                                   'sci_name="Sebastes jordani"')

# Change date format, add julian day
RREAS_list <- list(RREAS_hake, RREAS_sanddab, RREAS_anchovy, RREAS_widow, RREAS_shortbelly)
RREAS_list <- lapply(RREAS_list, function(x) {
  x$date <- as.Date(format(as.POSIXct(x$time, tz = "UTC", format = "%Y-%m-%d")))
  return(x)
  })
RREAS_list <- lapply(RREAS_list, function(x) {
  x %>% mutate(year = lubridate::year(date),
               month = lubridate::month(date),
               day = lubridate::day(date)) %>%
    mutate(julian = as.numeric(mdy.date(month, day, 1960)))
  })

# Lengths
length_hake <- extract_ERDDAP(RREAS_length_info, RREAS_length_list,
                             'sci_name="Merluccius productus"')
length_sanddab <- extract_ERDDAP(RREAS_length_info, RREAS_length_list,
                                'sci_name="Citharichthys sordidus"')
length_anchovy <- extract_ERDDAP(RREAS_length_info, RREAS_length_list,
                                'sci_name="Engraulis mordax"')
length_widow <- extract_ERDDAP(RREAS_length_info, RREAS_length_list,
                              'sci_name="Sebastes entomelas"')
length_shortbelly <- extract_ERDDAP(RREAS_length_info, RREAS_length_list,
                                   'sci_name="Sebastes jordani"')

# Change date format
length_list <- list(length_hake, length_sanddab, length_anchovy, length_widow, length_shortbelly)
length_list <- lapply(length_list, function(x) {
  x$date <- format(as.POSIXct(x$time, tz = "UTC", format = "%Y-%m-%d"))
  return(x)
  })
length_list <- lapply(length_list, function(x) {
  mutate(x, year = lubridate::year(date))
  })
```

CTD data from ERDDAP
```{r}
RREAS_CTD_info <- info('FED_Rockfish_CTD')

ctds <- tabledap(RREAS_CTD_info,
                 fields = c('cruise', 'ctd_index',
                            'temperature', 'salinity', 
                            'oxygen', 'station',
                            'ctd_depth'),
                 'ctd_depth<=10')

cols <- c('temperature', 'salinity', 'oxygen')
ctds[cols] <- sapply(ctds[cols], as.numeric)

ctd_means <- ctds  %>%
  group_by(cruise, ctd_index, station) %>%
  summarise_at(vars('temperature', 'salinity', 'oxygen'), mean) %>%
  mutate_all(~ifelse(is.nan(.), NA, .)) 
```

Add CTD to abundance data
```{r}
RREAS_list_env <- lapply(RREAS_list, function(x) merge(x, ctd_means,
                                                       by = c('cruise', 
                                                              'ctd_index',
                                                              'station'),
                                                       all.x = T))
```

Add length ratios
```{r}
# Filter based on years with length data
yoy_hake <- add_lengths(RREAS_list[[1]], length_list[[1]])
yoy_sanddab <- add_lengths(RREAS_list[[2]], length_list[[2]])
yoy_anchovy <- add_lengths(RREAS_list[[3]], length_list[[3]])
yoy_widow <- add_lengths(RREAS_list[[4]], length_list[[4]])
yoy_shortbelly <- add_lengths(RREAS_list[[5]], length_list[[5]])
```


Add climate indices
```{r}
# # NPGO
# npgo_index <- read.table("../data/npgo_data.txt",
#                          header = T)
# 
# # PDO
# pdo_index <- read.csv("../data/pdo_timeseries_ersstv5.csv")
# pdo_index$Date <- as.Date(pdo_index$Date, "%Y-%m-%d")
# pdo_index <- mutate(pdo_index,
#                     year = lubridate::year(Date),
#                     month = lubridate::month(Date))
# 
# # ONI
# oni_index <- read.table("../data/oni_data.txt",
#                         row.names = 1)
# colnames(oni_index) <- c("01", "02", "03", "04", 
#                          "05", "06", "07", "08", 
#                          "09", "10", "11", "12")
# oni_matrix <- melt(as.matrix(oni_index))
# colnames(oni_matrix) <- c("year", "month", "ONI")
# 
# # Means
# npgo_means <- npgo_index %>% 
#   filter(MONTH >= 1 & MONTH <= 3) %>%
#   group_by(YEAR) %>%
#   summarise(NPGO_mean = mean(NPGO))
# pdo_means <- pdo_index %>% 
#   filter(month >= 1 & month <= 3) %>%
#   group_by(year) %>%
#   summarise(PDO_mean = mean(PDO))
# oni_means <- oni_matrix %>% 
#   filter(month >= 1 & month <= 3) %>%
#   group_by(year) %>%
#   summarise(ONI_mean = mean(ONI))
# 
# # Match to dataframes
# yoy_hake_catch <- climate_match(yoy_hake_catch)
# yoy_dab_catch <- climate_match(yoy_dab_catch)
# adult_dab_catch <- climate_match(adult_dab_catch)
```


```{r}
# Save final dataframes
saveRDS(yoy_hake_catch, file = "../data/yoy_hake_catch.Rdata")
saveRDS(yoy_dab_catch, file = "../data/yoy_dab_catch.Rdata")
saveRDS(adult_dab_catch, file = "../data/adult_dab_catch.Rdata")
saveRDS(yoy_hake_sp, file = "../data/yoy_hake_sp.Rdata")
saveRDS(yoy_dab_sp, file = "../data/yoy_dab_sp.Rdata")
saveRDS(adult_dab_sp, file = "../data/adult_dab_sp.Rdata")
```


```{r, include = FALSE, echo = FALSE}
# Match specimen data to catch data
yoy_hake <- merge_data(yoy_hake_catch, yoy_hake_sp)
yoy_dab <- merge_data(yoy_dab_catch, yoy_dab_sp)
adult_dab <- merge_data(adult_dab_catch, adult_dab_sp) # not a lot of adult specimens compared to yoy
```

```{r, include = FALSE, echo = FALSE}
# Hake
par(mfrow = c(2, 3))
plot_variables(yoy_hake_catch)
```

```{r, include = FALSE, echo = FALSE}
# Sanddab
par(mfrow = c(2, 3))
plot_variables(yoy_dab_catch)

par(mfrow = c(2, 3))
plot_variables(adult_dab_catch)
```

```{r, include = FALSE, echo = FALSE}
# Look at pattern of days by latitude
ggplot(yoy_hake) +
  geom_point(aes(day, lat))
ggplot(yoy_dab) +
  geom_point(aes(day, lat))
ggplot(adult_dab) +
  geom_point(aes(day, lat))
```

```{r, include = FALSE, echo = FALSE}
ggplot(yoy_hake) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2)
ggplot(yoy_dab) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2) # one outlier >65 cm
ggplot(adult_dab) +
  geom_point(aes(bottom_depth, std_length),
                 alpha = 0.1,
                 size = 2) # two outliers found at >300 m depth
```

```{r, include = FALSE, echo = FALSE}
yoy_hake %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500, 3750))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

yoy_dab %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 250, 500, 750,
                                                  1000, 1250, 1500,
                                                  1750, 2000, 2250,
                                                  2500, 2750, 3000,
                                                  3250, 3500))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()

adult_dab %>%
  mutate(depth_cut = cut(bottom_depth, breaks = c(0, 50, 100, 150, 200,
                                                  250, 300, 350, 400,
                                                  450, 500, 550, 600, 
                                                  650, 700, 750, 800))) %>% 
  ggplot(aes(depth_cut, std_length)) +
  geom_boxplot()
```

```{r, include = FALSE, echo = FALSE}
# Filter out outliers
yoy_dab <- filter(yoy_dab, std_length < 65)
yoy_dab <- yoy_dab[!is.na(yoy_dab$bottom_depth), ]
adult_dab <- filter(adult_dab, bottom_depth < 300)
```

```{r, fig.width = 10, fig.height = 5, warning = FALSE, echo = FALSE}
# polish boxplot for depth/length
yoy_hake %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 3750, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Hake by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))

yoy_dab %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 3750, by = 250))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of YOY Sanddab by Depth") +
  scale_x_discrete(labels = c("0-250", "250-500", "500-750", "750-1000",
                              "1000-1250", "1250-1500", "1500-1750",
                              "1750-2000", "2000-2250", "2250-2500",
                              "2500-2750", "2750-3000", "3000-3250",
                              "3250-3500", "3500-3750")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))

adult_dab %>%
  mutate(depth_cut = cut(bottom_depth, breaks = seq(0, 300, by = 50))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, std_length),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Depth (m)",
       title = "Size of Adult Sanddab by Depth") +
  scale_x_discrete(labels = c("0-50", "50-100", "100-150", "150-200",
                              "200-250", "250-300")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r, include = FALSE, echo = FALSE}
# Investigate latitude
ggplot(yoy_hake) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2)
ggplot(yoy_dab) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2) # one outlier >65 cm
ggplot(adult_dab) +
  geom_point(aes(lat, std_length),
                 alpha = 0.1,
                 size = 2) # two outliers found at >300 m depth
```


```{r, include = FALSE, echo = FALSE}
yoy_hake %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

yoy_dab %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()

adult_dab %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot(aes(lat_cut, std_length)) +
  geom_boxplot()
```

```{r, fig.width = 10, fig.height = 5, warning = FALSE, echo = FALSE}
# polish boxplot for lat/length
yoy_hake %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Hake by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))

yoy_dab %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of YOY Sanddab by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))

adult_dab %>%
  mutate(lat_cut = cut(lat, breaks = seq(32, 48, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, std_length),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (mm)",
       x = "Latitude",
       title = "Size of Adult Sanddab by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7))
```

```{r, include = FALSE, echo = FALSE}
# Make maps of catches
west_coast <- map_data("usa")
```

```{r, warning = FALSE, echo = FALSE}
# YOY Hake
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

yoy_hakeplot1 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

yoy_hakeplot2 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

yoy_hakeplot3 <- ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_hake_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r}
grid.newpage()
# Create layout : nrow = 2, ncol = 2
pushViewport(viewport(layout = grid.layout(2, 2)))
# A helper function to define a region on the layout
define_region <- function(row, col){
  viewport(layout.pos.row = row, layout.pos.col = col)
} 
# Arrange the plots
print(yoy_hakeplot3, vp = define_region(2, 1:2))
print(yoy_hakeplot1, vp = define_region(1, 1))
print(yoy_hakeplot2, vp = define_region(1, 2))
```

```{r, warning = FALSE, echo = FALSE}
# YOY Sanddab
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = yoy_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

```{r, warning = FALSE, echo = FALSE}
ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = adult_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = adult_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -123), ylim = c(42, 48))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = adult_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-126, -120), ylim = c(35, 42))

ggplot() +  
  geom_polygon(aes(long, lat, group = group), data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  geom_point(data = adult_dab_catch, 
            aes(lon, lat,
                size = catch),
            color = "salmon") +
  coord_quickmap(xlim = c(-121.5, -117), ylim = c(32, 35))
```

