---
title: "WCGBTS Data Exploration"
author: "Rebecca Howard"
date: "8/2/2022"
output: html_document
---

```{r setup, include = FALSE}
### Load libraries
library(readxl)
library(plyr)
library(tibble)
library(here)
library(ggplot2)
library(lubridate)
library(date)
library(dplyr)
library(maps)
library(mapdata)
library(gridExtra)
library(grid)
library(reshape2)
```

Functions
```{r}
climate_match <- function(data){
  data <- merge(data, npgo_index,
                by.x = c("year", "month"),
                by.y = c("YEAR", "MONTH"),
                all.x = T, all.y = F)
  data <- merge(data, pdo_index,
                by.x = c("year", "month"),
                by.y = c("year", "month"),
                all.x = T, all.y = F)
  data <- subset(data, select = -c(Date))
  data <- merge(data, oni_matrix,
                by.x = c("year", "month"),
                by.y = c("year", "month"),
                all.x = T, all.y = F)
  match_npgo <- match(data$year, npgo_means$YEAR)
  data$NPGO_mean <- npgo_means$NPGO_mean[match_npgo]
  match_pdo <- match(data$year, pdo_means$year)
  data$PDO_mean <- pdo_means$PDO_mean[match_pdo]
  match_oni <- match(data$year, oni_means$year)
  data$ONI_mean <- oni_means$ONI_mean[match_oni]
  return(data)
}

merge_data <- function(data1, data2, data3){
  data_set <- merge(data2[, c("lncpue", "lncpue_n", "NPGO",
                         "PDO", "ONI", "NPGO_mean", "total_catch_numbers",
                         "PDO_mean", "ONI_mean", "cpue_kg",
                         "cpue_num", "trawl_id", "scientific_name")],
                    data1, 
                    by = c("trawl_id", "scientific_name"),
                    all = T)
  data_final <- merge(data3[, c("bottom_temp", "trawl_id")],
                      data_set, 
                      by = "trawl_id",
                      all.y = T)
  return(data_final)
}

plot_variables <- function(data_frame, species){
  data <- data_frame[data_frame$scientific_name == species, ]
  plot(table(data$year[data$lncpue_n > 0]),
       ylab = 'Frequency',
       xlab = 'Year',
       main = '')
  plot(table(data$doy[data$lncpue_n > 0]),
       ylab = 'Frequency',
       xlab = 'Day of Year',
       main = '')
  plot(table(data$latitude[data$lncpue_n > 0]),
       ylab = 'Frequency',
       xlab = 'Latitude',
       main = '')
  plot(table(data$longitude[data$lncpue_n > 0]),
       ylab = 'Frequency',
       xlab = 'Longitude',
       main = '')
  plot(table(data$depth_m[data$lncpue_n > 0]),
       ylab = 'Frequency',
       xlab = 'Depth',
       main = '')
  hist(data$lncpue_n, 
       breaks = 100,
       main = '',
       xlab = 'ln(CPUE + 1)') 
}
```

Data cleaning
```{r, include = FALSE, echo = FALSE}
# Load biological data
options(scipen = 999) # removes scientific notation for trawl ID
WCGBTS_catch <- read.csv(here('data', 'WCGBTS_catch.csv'), 
                         na.strings = c("", NA),
                         fileEncoding = "UTF-8-BOM")
WCGBTS_specimens <- read.csv(here('data', 'WCGBTS_specimens.csv'), 
                         header = T,
                         fileEncoding = "UTF-8-BOM")
WCGBTS_hauls <- read.csv(here('data', 'WCGBTS_hauls.csv'), 
                         header = T,
                         fileEncoding = "UTF-8-BOM")

# NPGO
npgo_index <- read.table("../data/npgo_data.txt",
                         header = T)

# PDO
pdo_index <- read.csv("../data/pdo_timeseries_ersstv5.csv")
pdo_index$Date <- as.Date(pdo_index$Date, "%Y-%m-%d")
pdo_index <- mutate(pdo_index,
                    year = lubridate::year(Date),
                    month = lubridate::month(Date))

# ONI
oni_index <- read.table("../data/oni_data.txt",
                        row.names = 1)
colnames(oni_index) <- c("01", "02", "03", "04", 
                         "05", "06", "07", "08", 
                         "09", "10", "11", "12")
oni_matrix <- melt(as.matrix(oni_index))
colnames(oni_matrix) <- c("year", "month", "ONI")

# Means
npgo_means <- npgo_index %>% 
  filter(MONTH >= 1 & MONTH <= 3) %>%
  group_by(YEAR) %>%
  summarise(NPGO_mean = mean(NPGO))
pdo_means <- pdo_index %>% 
  filter(month >= 1 & month <= 3) %>%
  group_by(year) %>%
  summarise(PDO_mean = mean(PDO))
oni_means <- oni_matrix %>% 
  filter(month >= 1 & month <= 3) %>%
  group_by(year) %>%
  summarise(ONI_mean = mean(ONI))
```

```{r}
# Filter data
# Which surveys do we want? Currently just sticking with the WCGBTS beginning in 2003
# Not limiting by latitude or depth
# Reduce datasets to only include species of interest (hake, sanddab, anchovy, shortbelly, widow)
unique(WCGBTS_catch$project)
species <- c("Merluccius productus", 
             "Citharichthys sordidus",
             "Engraulis mordax",
             "Sebastes jordani",
             "Sebastes entomelas")

WCGBTS_catch$date <- as.Date(as.character(WCGBTS_catch$date_yyyymmdd), "%Y%m%d")
WCGBTS_specimens$date <- as.Date(as.character(WCGBTS_specimens$date_yyyymmdd), "%Y%m%d")
WCGBTS_hauls$date <- as.Date(as.character(WCGBTS_hauls$date_yyyymmdd), "%Y%m%d")

WCGBTS_samples <- WCGBTS_catch %>% 
  rename(c(cpue_kg = cpue_kg_per_ha_der,
           cpue_num = cpue_numbers_per_ha_der,
           latitude = latitude_dd,
           longitude = longitude_dd)) %>%
  filter(project == "Groundfish Slope and Shelf Combination Survey",
         performance != "Unsatisfactory",
         scientific_name %in% species) %>%
  mutate(month = lubridate::month(date),
         day = lubridate::day(date),
         doy = as.numeric(mdy.date(month, day, 1960)),
         lncpue = log(cpue_kg + 1),
         lncpue_n = log(cpue_num + 1)) 

WCGBTS_individuals <- WCGBTS_specimens %>%
  rename(c(latitude = latitude_dd,
           longitude = longitude_dd)) %>% 
  filter(project == "Groundfish Slope and Shelf Combination Survey",
         performance != "Unsatisfactory",
         scientific_name %in% species) %>%
  mutate(month = lubridate::month(date),
         day = lubridate::day(date),
         doy = as.numeric(mdy.date(month, day, 1960))) 

WCGBTS_tows <- WCGBTS_hauls %>%
  rename(c(latitude = latitude_dd,
           longitude = longitude_dd,
           depth_m = depth_hi_prec_m,
           year = date_dim.year,
           bottom_temp = temperature_at_gear_c_der)) %>% 
  filter(project == "Groundfish Slope and Shelf Combination Survey",
         performance != "Unsatisfactory") %>%
  mutate(month = lubridate::month(date),
         day = lubridate::day(date),
         doy = as.numeric(mdy.date(month, day, 1960))) 
```

```{r}
# Add environmental data to the catch and haul data
WCGBTS_samps <- climate_match(WCGBTS_samples)
WCGBTS_samps <- merge(WCGBTS_samps, 
                      WCGBTS_tows[c("bottom_temp",
                                    "trawl_id")],
                      by = "trawl_id")
WCGBTS_summary <- climate_match(WCGBTS_tows)
```

```{r}
# Match individuals with samples
WCGBTS_combined <- merge_data(WCGBTS_individuals, WCGBTS_samps, WCGBTS_summary)
```


```{r}
# Save new dataframes
saveRDS(WCGBTS_samps, file = "../data/WCGBTS_samps.Rdata")
saveRDS(WCGBTS_individuals, file = "../data/WCGBTS_individuals.Rdata") # not available for anchovy
saveRDS(WCGBTS_summary, file = "../data/WCGBTS_summary.Rdata")
saveRDS(WCGBTS_combined, file = "../data/WCGBTS_combined.Rdata")
```


Data exploration
```{r}
# Hake
par(mfrow = c(2, 3))
plot_variables(WCGBTS_samps, "Merluccius productus")

nrow(WCGBTS_samps[WCGBTS_samps$lncpue_n > 0 & WCGBTS_samps$scientific_name == "Merluccius productus", ])
```

```{r}
# Sanddab
par(mfrow = c(2, 3))
plot_variables(WCGBTS_samps, "Citharichthys sordidus")

nrow(WCGBTS_samps[WCGBTS_samps$lncpue_n > 0 & WCGBTS_samps$scientific_name == "Citharichthys sordidus", ])
```

```{r}
# Anchovy
par(mfrow = c(2, 3))
plot_variables(WCGBTS_samps, "Engraulis mordax")

nrow(WCGBTS_samps[WCGBTS_samps$lncpue_n > 0 & WCGBTS_samps$scientific_name == "Engraulis mordax", ])
```

```{r}
# Shortbelly Rockfish
par(mfrow = c(2, 3))
plot_variables(WCGBTS_samps, "Sebastes jordani")

nrow(WCGBTS_samps[WCGBTS_samps$lncpue_n > 0 & WCGBTS_samps$scientific_name == "Sebastes jordani", ])
```

```{r}
# Widow Rockfish
par(mfrow = c(2, 3))
plot_variables(WCGBTS_samps, "Sebastes entomelas")

nrow(WCGBTS_samps[WCGBTS_samps$lncpue_n > 0 & WCGBTS_samps$scientific_name == "Sebastes entomelas", ])
```

```{r}
# Look at pattern of days by latitude
ggplot(WCGBTS_samps, aes(day, latitude)) +
  geom_point() +
  facet_wrap(~ scientific_name)
```

```{r, warning = F}
# Look at pattern of lengths
ggplot(WCGBTS_individuals, 
       aes(depth_m, length_cm)) + # depth
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name) # smaller at shallower depths for sebastes spp

ggplot(WCGBTS_individuals, 
       aes(year, length_cm)) + # year
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name)

ggplot(WCGBTS_individuals, 
       aes(doy, length_cm)) + # doy
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name)

ggplot(WCGBTS_individuals, 
       aes(latitude, length_cm)) + # latitude
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name) # slightly larger further north
```

```{r, warning = F}
ggplot(WCGBTS_individuals, 
       aes(depth_m, age_years)) + # depth
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name) # younger individuals in shallower water for sebastes spp

ggplot(WCGBTS_individuals, 
       aes(year, age_years)) + # year
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name) # age data not available for all species for all years

ggplot(WCGBTS_individuals, 
       aes(doy, age_years)) + # doy
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name)

ggplot(WCGBTS_individuals, 
       aes(latitude, age_years)) + # latitude
  geom_point(alpha = 0.1,
             size = 2) +
  facet_wrap(~ scientific_name) # slightly older individuals further north for sanddab, widow
```


```{r, warning = F}
WCGBTS_individuals %>%
  mutate(depth_cut = cut(depth_m, breaks = c(0, 150, 300, 450, 600,
                                             750, 900, 1050, 1200))) %>% 
  ggplot(aes(depth_cut, length_cm)) +
  geom_boxplot() +
  facet_wrap(~ scientific_name)
```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(depth_cut = cut(depth_m, breaks = seq(0, 1350, by = 150))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, length_cm),
               fill = "darkseagreen3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (cm)",
       x = "Depth (m)",
       title = "Length by Depth") +
  scale_x_discrete(labels = c("0-150", "150-300", "300-450", "450-600",
                              "600-750", "750-900", "900-1050", "1050-1200",
                              "1200-1350")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)

```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(lat_cut = cut(latitude, breaks = seq(32, 48, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, length_cm),
               fill = "cyan3", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (cm)",
       x = "Latitude",
       title = "Length by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)

```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(doy_cut = cut(doy, breaks = seq(135, 300, by = 15))) %>% 
  ggplot() +
  geom_boxplot(aes(doy_cut, length_cm),
               fill = "plum4", 
               outlier.alpha = 0.2) +  
  labs(y = "Length (cm)",
       x = "Day of Year",
       title = "Length by Day of Year") +
  scale_x_discrete(labels = c("135-150", "150-165", "165-180", "180-195",
                              "195-210", "210-225", "225-240", "240-255",
                              "255-270", "270-285", "285-300")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)
```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(depth_cut = cut(depth_m, breaks = seq(0, 1350, by = 150))) %>% 
  ggplot() +
  geom_boxplot(aes(depth_cut, age_years),
               fill = "darksalmon", 
               outlier.alpha = 0.2) +  
  labs(y = "Age (years)",
       x = "Depth (m)",
       title = "Age by Depth") +
  scale_x_discrete(labels = c("0-150", "150-300", "300-450", "450-600",
                              "600-750", "750-900", "900-1050", "1050-1200",
                              "1200-1350")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)
```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(lat_cut = cut(latitude, breaks = seq(32, 48, by = 1))) %>% 
  ggplot() +
  geom_boxplot(aes(lat_cut, age_years),
               fill = "goldenrod1", 
               outlier.alpha = 0.2) +  
  labs(y = "Age (years)",
       x = "Latitude",
       title = "Age by Latitude") +
  scale_x_discrete(labels = c("32-33", "33-34", "34-35", "35-36", "36-37",
                              "37-38", "38-39", "39-40", "40-41", "41-42",
                              "42-43", "43-44", "44-45", "45-46", "46-47",
                              "47-48", "48-49")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)
```

```{r, fig.width = 20, fig.height = 15, warning = FALSE, echo = FALSE}
WCGBTS_individuals %>%
  mutate(doy_cut = cut(doy, breaks = seq(135, 300, by = 15))) %>% 
  ggplot() +
  geom_boxplot(aes(doy_cut, age_years),
               fill = "lightpink", 
               outlier.alpha = 0.2) +  
  labs(y = "Age (years)",
       x = "Day of Year",
       title = "Age by Day of Year") +
  scale_x_discrete(labels = c("135-150", "150-165", "165-180", "180-195",
                              "195-210", "210-225", "225-240", "240-255",
                              "255-270", "270-285", "285-300")) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18)) +
  facet_wrap(~ scientific_name)
```


```{r, include = FALSE, echo = FALSE}
# Make maps of catches
west_coast <- map_data("usa")
```

```{r, warning = FALSE, echo = FALSE, fig.width = 15, fig.height = 20}
ggplot() +  
    geom_point(data = WCGBTS_samps, 
            aes(longitude, latitude,
                size = lncpue_n),
            color = "salmon",
            alpha = 0.2) +
  labs(y = "Latitude",
       x = "Longitude",
       size = "ln(CPUE+1)") +
  geom_polygon(aes(long, lat, group = group), 
               data = west_coast,
               fill = "lightyellow4", 
               colour = "black") +
  coord_quickmap(xlim = c(-126, -117), ylim = c(32, 48)) +
  theme_classic() +
  theme(panel.background = element_rect(fill = "gray91", colour = "gray91"),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(size = 22, family = "serif", face = "bold"),
        axis.text = element_text(family = "serif", size = 14),
        axis.title = element_text(family = "serif", size = 18),
        axis.text.x = element_text(angle = 45, vjust = 0.7),
        strip.text = element_text(family = "serif", size = 18),
        legend.title = element_text(family = "serif", size = 16),
        legend.text = element_text(family = "serif", size = 14)) +
  facet_wrap(~ scientific_name)
```
