---
title: "WCGBTS Model Exploration"
author: "Rebecca Howard"
date: "8/3/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
### Load libraries
library(readxl)
library(plyr)
library(tibble)
library(here)
library(ggplot2)
library(lubridate)
library(date)
library(dplyr)
library(maps)
library(mapdata)
library(mgcv)
library(fields)
library(colorspace)
source("functions/vis_gam_COLORS.R")
```

Load data
```{r}
# Load data
options(scipen = 999)
WCGBTS_data <- readRDS(file = "../data/WCGBTS_samps.Rdata")
WCGBTS_tows <- readRDS(file = "../data/WCGBTS_summary.Rdata")
WCGBTS_indvs <- readRDS(file = "../data/WCGBTS_combined.Rdata")
```

Convert climate indices to positive values
```{r}
WCGBTS_data$NPGO_pos <- WCGBTS_data$NPGO_mean + abs(min(WCGBTS_data$NPGO_mean))
WCGBTS_data$PDO_pos <- WCGBTS_data$PDO_mean + abs(min(WCGBTS_data$PDO_mean))
WCGBTS_data$ONI_pos <- WCGBTS_data$ONI_mean + abs(min(WCGBTS_data$ONI_mean))

WCGBTS_tows$NPGO_pos <- WCGBTS_tows$NPGO_mean + abs(min(WCGBTS_tows$NPGO_mean))
WCGBTS_tows$PDO_pos <- WCGBTS_tows$PDO_mean + abs(min(WCGBTS_tows$PDO_mean))
WCGBTS_tows$ONI_pos <- WCGBTS_tows$ONI_mean + abs(min(WCGBTS_tows$ONI_mean))
```

Functions
```{r}
# Histogram of catches
CPUE_hist <- function(species_subset){
  par(mfrow = c(1,2))
  hist(species_subset$lncpue,
       xlab = "log(CPUE + 1)",
       main = "Raw Data")
  sum(1 * (species_subset$lncpue_n == 0)) / nrow(species_subset)
  hist(species_subset$lncpue_n[species_subset$lncpue > 0],
    xlab = "log(CPUE + 1)",
    main = "Normalized Data")
}

# Subset data for each species
subset_species <- function(species, catch, tows){
  subset <- catch[catch$scientific_name == species, ]
  match_id <- match(tows$trawl_id, subset$trawl_id)
  tows$lncpue_n <- subset$lncpue_n[match_id]
  tows$lncpue_n[is.na(tows$lncpue_n)] <- 0
  tows$catch <- subset$total_catch_numbers[match_id]
  tows$catch[is.na(tows$catch)] <- 0
  selected_species <- select(tows, doy, year, lncpue_n, latitude, longitude, 
                             PDO, NPGO, ONI, bottom_temp, depth_m, PDO_pos,
                             NPGO_pos, ONI_pos, catch, trawl_id)
  selected_species <- na.omit(selected_species)
  selected_species$pres <- 1 * (selected_species$lncpue_n > 0)
  return(selected_species)
}

# Gaussian GAMs
cpue_GAMs <- function(species_subset){
  year_gam <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4),
                  data = species_subset[species_subset$lncpue_n > 0,])
  pdo_gam <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                   s(bottom_temp, k = 4) + s(PDO, k = 4),
                  data = species_subset[species_subset$lncpue_n > 0,])
  npgo_gam <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(NPGO, k = 4),
                  data = species_subset[species_subset$lncpue_n > 0,])
  oni_gam <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                   s(bottom_temp, k = 4) + s(ONI, k = 4),
                  data = species_subset[species_subset$lncpue_n > 0,])
  pdo_flex <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(latitude, longitude, by = PDO_pos),
                  data = species_subset[species_subset$lncpue_n > 0,])
  npgo_flex <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                     s(bottom_temp, k = 4) + s(latitude, longitude, by = NPGO_pos),
                  data = species_subset[species_subset$lncpue_n > 0,])
  oni_flex <- gam(lncpue_n ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(latitude, longitude, by = ONI_pos),
                  data = species_subset[species_subset$lncpue_n > 0,])
  gam_list <- list(year_gam, pdo_gam, npgo_gam, oni_gam, pdo_flex, npgo_flex, oni_flex)
  best_gam <- gam_list[[which.min(sapply(1:length(gam_list),
                                         function(x) min(gam_list[[x]]$aic)))]] 
  return_list <- list(gam_list, best_gam)
} 

# Tweedie GAMs
tweedie_GAMs <- function(species_subset){
  year_gam <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  pdo_gam <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                   s(bottom_temp, k = 4) + s(PDO, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  npgo_gam <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(NPGO, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  oni_gam <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                   s(bottom_temp, k = 4) + s(ONI, k = 4),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  pdo_flex <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(latitude, longitude, by = PDO_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  npgo_flex <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                     s(bottom_temp, k = 4) + s(latitude, longitude, by = NPGO_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  oni_flex <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) + s(doy) + 
                    s(bottom_temp, k = 4) + s(latitude, longitude, by = ONI_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = species_subset)
  gam_list <- list(year_gam, pdo_gam, npgo_gam, oni_gam, pdo_flex, npgo_flex, oni_flex)
  best_gam <- gam_list[[which.min(sapply(1:length(gam_list),
                                         function(x) min(gam_list[[x]]$aic)))]] 
  return_list <- list(gam_list, best_gam)
} 

# Calculate variable coefficient term 
variable_coefficient <- function(gam, data, variable){
  preds <- predict(gam[[2]], type = 'terms', se.fit = T)
  pred_slope <- preds[[1]][, 5] / variable
  pred_slope_se <- 1.96 * preds[[2]][, 5]
  pred_slope_up <- (preds[[1]][, 5] + pred_slope_se) / variable
  pred_slope_low <- (preds[[1]][, 5] - pred_slope_se) / variable
  sign_slope_pos <- (1:length(pred_slope))[pred_slope_low > 0]
  sign_slope_neg <- (1:length(pred_slope))[pred_slope_up < 0]
  return(list(sign_slope_neg, sign_slope_pos, pred_slope))
}

variable_coefficient_lengths <- function(gam, data, variable){
  preds <- predict(gam, type = 'terms', se.fit = T)
  pred_slope <- preds[[1]][, 5] / variable
  pred_slope_se <- 1.96 * preds[[2]][, 5]
  pred_slope_up <- (preds[[1]][, 5] + pred_slope_se) / variable
  pred_slope_low <- (preds[[1]][, 5] - pred_slope_se) / variable
  sign_slope_pos <- (1:length(pred_slope))[pred_slope_low > 0]
  sign_slope_neg <- (1:length(pred_slope))[pred_slope_up < 0]
  return(list(sign_slope_neg, sign_slope_pos, pred_slope))
}

# Combine length data with trawl data
merge_data <- function(data1, data2){
  merge(data1, data2,
        by = "trawl_id",
        all.x = F, all.y = T)
}

# Plot smooth terms
plot_variable <- function(gam, covariate, bounds, variable, ylabel, yvalues){
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  plot(gam[[2]],
       pages = 0,
       select = covariate, # 1 = year/PDO/NPGO, 2 = latitude/longitude, 3 = depth, 4 = julian, 5 = temp
       shade = T,
       shade.col = "lemonchiffon3",
       ylim = bounds,
       xlab = variable,
       ylab = ylabel,
       yaxt = yvalues,
       seWithMean = T,
       scale = 0,
       cex.axis = 3,
       cex.lab = 3,
       family = "serif",
       lwd = 2)
}

location_plot <- function(gam, species_subset) {
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  myvis_gam(gam[[2]],
            view = c('longitude', 'latitude'),
            too.far = 0.07,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet" ,
            type = 'link',
            xlim = c(-125.7, -116.5),
            ylim = range(species_subset$latitude, na.rm = TRUE) + c(-.4, .5),
            family = "serif",
            xlab = "longitude",
            ylab = "latitude",
            main = " ",
            cex.lab = 2.5,
            cex.axis =  2.5)
  maps::map('worldHires',
            add = T,
            col = 'antiquewhite4',
            fill = T)
  image.plot(legend.only = T,
           col = jet.colors(100),
           legend.shrink = 0.2,
           smallplot = c(.28, .31, .11, .24),
           legend.cex = 1.3,
           axis.args = list(cex.axis = 1.8,
                            family = "serif"),
           legend.width = 0.8,
           legend.mar = 6,
           zlim = c(min(gam[[2]]$linear.predictors), 
                    max(gam[[2]]$linear.predictors)),
           legend.args = list("log(count+1)",
                              side = 2, cex = 2,
                              family = "serif"))
}

# Plot variable coefficient term
plot_var_coef <- function(gam, data, predictions){
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  myvis_gam(gam[[2]],
            view = c('longitude', 'latitude'),
            too.far = 0.07,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet" ,
            type = 'link',
            xlim = c(-125.7,-116.5),
            ylim = range(data$latitude, na.rm = TRUE) + c(-.4, .5),
            family = "serif",
            xlab = "longitude",
            ylab = "latitude",
            main = " ",
            cex.lab = 2.5,
            cex.axis =  2.5)
  symbols(data$longitude[predictions[[2]]],
          data$latitude[predictions[[2]]],
          circle = predictions[[3]][predictions[[2]]],
          inches = 0.12,
          add = T,
          bg = alpha('darkred', 0.4),
          fg = alpha('black', 0.08))
  symbols(data$longitude[predictions[[1]]],
          data$latitude[predictions[[1]]],
          circle = (-1) * predictions[[3]][predictions[[1]]],
          inches = 0.12,
          add = T,
          bg = alpha('navy', 0.4),
          fg = alpha('black', 0.08))
  map("worldHires",
      fill = T,
      col = "wheat4",
      add = T)
  image.plot(legend.only = T,
             col = jet.colors(100),
             legend.shrink = 0.2,
             smallplot = c(.28, .31, .11, .24),
             legend.cex = 1.3,
             axis.args = list(cex.axis = 1.8,
                              family = "serif"),
             legend.width = 0.8,
             legend.mar = 6,
             zlim = c(min(gam[[2]]$linear.predictors),
                      max(gam[[2]]$linear.predictors)),
             legend.args = list("log(count+1)",
                                side = 2, cex = 2,
                                family = "serif"))
}

plot_var_coef_lengths <- function(gam, data, predictions){
  par(mar = c(6.4, 7.2, .5, 0.6) + 0.1,
      oma = c(1, 1, 1, 1),
      mgp = c(5, 2, 0))
  myvis_gam(gam,
            view = c('longitude', 'latitude'),
            too.far = 0.07,
            plot.type = 'contour',
            contour.col = contour_col,
            color = "jet" ,
            type = 'link',
            xlim = c(-125.7, -116.5),
            ylim = range(data$lat, na.rm = TRUE) + c(-.4, .5),
            family = "serif",
            xlab = "Longitude",
            ylab = "Latitude",
            main = " ",
            cex.lab = 2.5,
            cex.axis =  2.5)
  symbols(data$lon[predictions[[2]]],
          data$lat[predictions[[2]]],
          circle = predictions[[3]][predictions[[2]]],
          inches = 0.12,
          add = T,
          bg = alpha('darkred', 0.4),
          fg = alpha('black', 0.08))
  symbols(data$lon[predictions[[1]]],
          data$lat[predictions[[1]]],
          circle = (-1) * predictions[[3]][predictions[[1]]],
          inches = 0.12,
          add = T,
          bg = alpha('navy', 0.4),
          fg = alpha('black', 0.08))
  map("worldHires",
      fill = T,
      col = "wheat4",
      add = T)
  image.plot(legend.only = T,
             col = jet.colors(100),
             legend.shrink = 0.2,
             smallplot = c(.28, .31, .11, .24),
             legend.cex = 1.3,
             axis.args = list(cex.axis = 1.8,
                              family = "serif"),
             legend.width = 0.8,
             legend.mar = 6,
             zlim = c(min(gam$linear.predictors),
                      max(gam$linear.predictors)),
             legend.args = list("log(count+1)",
                                side = 2, cex = 2,
                                family = "serif"))
}

contour_col <- rgb(0, 0, 255, max = 255, alpha = 0, names = "white")
jet.colors <- colorRampPalette(c(sequential_hcl(15, palette = "Mint")))
```


Create species datasets
```{r}
hake_data <- subset_species("Merluccius productus", WCGBTS_data, WCGBTS_tows)
dab_data <- subset_species("Citharichthys sordidus", WCGBTS_data, WCGBTS_tows)
anch_data <- subset_species("Engraulis mordax", WCGBTS_data, WCGBTS_tows)
sbly_data <- subset_species("Sebastes jordani", WCGBTS_data, WCGBTS_tows)
widw_data <- subset_species("Sebastes entomelas", WCGBTS_data, WCGBTS_tows)
```


#### Gaussian on positive catches
### Adult Hake
```{r}
# Explore simple GAM
hake_base <- gam(lncpue_n ~ factor(year) +
                   s(doy) +
                   s(latitude, longitude) +
                   s(depth_m, k = 4) +
                   s(bottom_temp, k = 4),
                 data = hake_data[hake_data$lncpue_n > 0, ])
summary(hake_base)

par(mfrow = c(2, 2))
gam.check(hake_base)

par(mfrow = c(2, 2))
plot(hake_base)

# Select best GAM
# Select best GAM
hake_gam <- cpue_GAMs(hake_data)
summary(hake_gam[[2]])

par(mfrow = c(2, 2))
gam.check(hake_gam[[2]])

par(mfrow = c(2, 2))
plot(hake_gam[[2]])
```

### Adult Sanddab
```{r}
# Explore simple GAM
dab_base <- gam(lncpue_n ~ factor(year) +
                   s(doy) +
                   s(latitude, longitude) +
                   s(depth_m, k = 4) +
                   s(bottom_temp, k = 4),
                 data = dab_data[dab_data$lncpue_n > 0, ])
summary(dab_base)

par(mfrow = c(2, 2))
gam.check(dab_base)

par(mfrow = c(2, 2))
plot(dab_base)

# Select best GAM
# Select best GAM
dab_gam <- cpue_GAMs(dab_data)
summary(dab_gam[[2]])

par(mfrow = c(2, 2))
gam.check(dab_gam[[2]])

par(mfrow = c(2, 2))
plot(dab_gam[[2]])
```


### Adult Anchovy
```{r}
# Explore simple GAM
anch_base <- gam(lncpue_n ~ factor(year) +
                   s(doy) +
                   s(latitude, longitude) +
                   s(depth_m, k = 4) +
                   s(bottom_temp, k = 4),
                 data = anch_data[anch_data$lncpue_n > 0, ])
summary(anch_base)

par(mfrow = c(2, 2))
gam.check(anch_base)

par(mfrow = c(2, 2))
plot(anch_base)

# Select best GAM
# Select best GAM
anch_gam <- cpue_GAMs(anch_data)
summary(anch_gam[[2]])

par(mfrow = c(2, 2))
gam.check(anch_gam[[2]])

par(mfrow = c(2, 2))
plot(anch_gam[[2]])
```


### Adult Shortbelly
```{r}
# Explore simple GAM
sbly_base <- gam(lncpue_n ~ factor(year) +
                   s(doy) +
                   s(latitude, longitude) +
                   s(depth_m, k = 4) +
                   s(bottom_temp, k = 4),
                 data = sbly_data[sbly_data$lncpue_n > 0, ])
summary(sbly_base)

par(mfrow = c(2, 2))
gam.check(sbly_base)

par(mfrow = c(2, 2))
plot(sbly_base)

# Select best GAM
# Select best GAM
sbly_gam <- cpue_GAMs(sbly_data)
summary(sbly_gam[[2]])

par(mfrow = c(2, 2))
gam.check(sbly_gam[[2]])

par(mfrow = c(2, 2))
plot(sbly_gam[[2]])
```


### Adult Widow
```{r}
# Explore simple GAM
widw_base <- gam(lncpue_n ~ factor(year) +
                   s(doy) +
                   s(latitude, longitude) +
                   s(depth_m, k = 4) +
                   s(bottom_temp, k = 4),
                 data = widw_data[widw_data$lncpue_n > 0, ])
summary(widw_base)

par(mfrow = c(2, 2))
gam.check(widw_base)

par(mfrow = c(2, 2))
plot(widw_base)

# Select best GAM
# Select best GAM
widw_gam <- cpue_GAMs(widw_data)
summary(widw_gam[[2]])

par(mfrow = c(2, 2))
gam.check(widw_gam[[2]])

par(mfrow = c(2, 2))
plot(widw_gam[[2]])
```


#### Tweedie
### Adult Hake
```{r}
# Base GAM
hake_base_t <- gam(catch + 1 ~ factor(year) +
                     s(doy) +
                     s(latitude, longitude) +
                     s(depth_m, k = 4) +
                     s(bottom_temp, k = 4),
                 family = tw(link = "log"),
                 method = 'REML',
                 data = hake_data)
summary(hake_base_t)

par(mfrow = c(2, 2))
gam.check(hake_base_t)

par(mfrow = c(2, 2))
plot(hake_base_t)


# Select best GAM
hake_gam_t <- tweedie_GAMs(hake_data)
summary(hake_gam_t[[2]])

par(mfrow = c(2, 2))
gam.check(hake_gam_t[[2]])

par(mfrow = c(2, 2))
plot(hake_gam_t[[2]])
```

```{r}
pred_hake_t <- variable_coefficient(hake_gam_t, hake_data, hake_data$NPGO_pos)

plot_var_coef(hake_gam_t, hake_data, pred_hake_t)
dev.copy(jpeg, here('results/WCGBTS_preliminary', 'adult_hake_var_coef.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```

Size-specific models
```{r}
# Split into two data frames for small and large individuals
hake_lengths <- WCGBTS_indvs %>%
  filter(scientific_name == "Merluccius productus")

hist(hake_lengths$length_cm) # Check to see where to make the split

hake_lower <- aggregate(length_cm ~ trawl_id, 
                        data = hake_lengths, 
                        FUN = length, 
                        subset = length_cm <= 40)
hake_adults <- merge_data(hake_lower, hake_data)
names(hake_adults)[names(hake_adults) == "length_cm"] <- "lower_num"

hake_upper <- aggregate(length_cm ~ trawl_id, 
                        data = hake_lengths, 
                        FUN = length, 
                        subset = length_cm > 40)
hake_adults <- merge_data(hake_upper, hake_adults)
names(hake_adults)[names(hake_adults) == "length_cm"] <- "upper_num"

hake_total <- aggregate(length_cm ~ trawl_id, 
                        data = hake_lengths, 
                        FUN = length)
hake_adults<- merge_data(hake_total, hake_adults)
names(hake_adults)[names(hake_adults) == "length_cm"] <- "total_num"

# Calculate how much of the catch comes from small/large individuals
hake_adults$upper_count <- (hake_adults$upper_num / hake_adults$total_num) * hake_adults$catch
hake_adults$lower_count <- (hake_adults$lower_num / hake_adults$total_num) * hake_adults$catch

hake_adults$upper_count[is.na(hake_adults$upper_count)] <- 0
hake_adults$lower_count[is.na(hake_adults$lower_count)] <- 0
```

```{r}
# Best model from full data set is as below
hake_all <- gam(catch + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) +
                  s(doy) + s(bottom_temp, k = 4) + s(latitude, longitude, by = NPGO_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = hake_adults)
hake_small <- gam(lower_count + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) +
                    s(doy) + s(bottom_temp, k = 4) + s(latitude, longitude, by = NPGO_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = hake_adults)
hake_large <- gam(upper_count + 1 ~ factor(year) + s(longitude, latitude) + s(depth_m, k = 4) +
                    s(doy) + s(bottom_temp, k = 4) + s(latitude, longitude, by = NPGO_pos),
                  family = tw(link = "log"),
                  method = 'REML',
                  data = hake_adults)
summary(hake_all) # 45.5% deviance explained 
summary(hake_small) # 45% deviance explained
summary(hake_large) # 48.8% deviance explained
```

```{r}
pred_adult_hake_lower <- variable_coefficient_lengths(hake_small, hake_adults, hake_adults$NPGO_pos)

plot_var_coef_lengths(hake_small, hake_adults, pred_adult_hake_lower)
dev.copy(jpeg, here('results/WCGBTS_preliminary', 'adult_hake_var_coef_lower.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```

```{r}
pred_adult_hake_upper <- variable_coefficient_lengths(hake_large, hake_adults, hake_adults$NPGO_pos)

plot_var_coef_lengths(hake_large, hake_adults, pred_adult_hake_upper)
dev.copy(jpeg, here('results/WCGBTS_preliminary', 'adult_hake_var_coef_upper.jpg'), 
         height = 15, width = 8, units = 'in', res = 200)
dev.off()
```